apiVersion: v1
kind: Service
metadata:
  name: {{ include "preview.name" . }}
  labels:
    {{- include "preview.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "preview.selectorLabels" . | nindent 4 }}
