remote = true

models = [
    "openai-community/gpt2",
    "EleutherAI/gpt-j-6b",
    "meta-llama/Llama-3.1-8B",
    "meta-llama/Llama-3.1-70B",
    "meta-llama/Llama-3.1-70B-Instruct",
    "meta-llama/Llama-3.3-70B-Instruct",
    "meta-llama/Llama-3.1-405B-Instruct",
    "meta-llama/Llama-3.1-405B",
    "meta-llama/Llama-2-7b-hf",
]
