name: Modal

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Modal
        run: |
          python -m pip install --upgrade pip
          pip install modal

      - name: Deploy to Modal
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            export MODAL_APP_NAME="interp-workbench-prod" ENVIRONMENT="prod"
          elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            export MODAL_APP_NAME="interp-workbench-dev"
          fi
          modal deploy modal/image.py